EWB-4105: Update super pom to 0.34.1
zepben/evolve-conn-jvm pull request #12
Opened 2023-11-27 01:22 UTC by Lax125

# Description

Use super pom version 0.34.1. This comes with breaking changes for Vert.x.

# Associated tasks

Tasks blocking this one:
- [ ] https://github.com/zepben/evolve-super-pom/pull/36
- [ ] https://github.com/zepben/test-utils-jvm/pull/4
- [ ] https://github.com/zepben/vertx-utils/pull/3

Tasks this is blocking:
- Update super pom version in evolve-sdk (PR TBA)

# Checklist

If any of these are not applicable, strikethrough the line `~like this~`. **Do not delete it!**. Let the reviewer decide if you should have done it.

### Code
- [ ] I have performed a self review of my own code (including checking issues raised when creating the PR).
- [ ] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.
- [ ] ~I have commented my code in any hard-to-understand or hacky areas.~
- [ ] I have handled all new warnings generated by the compiler or IDE.
- [ ] I have rebased onto the target branch (usually main).
      
### Documentation
- [x] I have updated the changelog.
- [ ] ~I have updated any documentation required for these changes.~

# Breaking Changes
- [x] I have considered if this is a breaking change and will communicate it with other team members if so.

Updates Vert.x major version (3 -> 4).

2023-11-27 01:22 UTC, ryanjcoleman commented
Task linked: [EWB-4105 Update evolve conn jvm](https://app.clickup.com/t/6929263/EWB-4105)

2023-11-28 00:52 UTC, Lax125 commented
Will fix up some sections using deprecated functions

2023-11-28 04:20 UTC, Lax125 commented
Looks like auth config route is still needed...

2023-11-29 03:51 UTC, Lax125 commented on src/main/kotlin/com/zepben/auth/server/AuthConfigRoute.kt
> +    val issuer: String,
`ewb-web-client` currently uses the `issuer` field in the auth config json.

2023-12-18 03:29 UTC, charlta requested changes

2023-12-18 03:29 UTC, charlta commented on src/test/kotlin/com/zepben/auth/server/AuthConfigRouteTest.kt
todo: This file should not have been removed

2023-12-19 00:48 UTC, Lax125 commented on src/test/kotlin/com/zepben/auth/server/AuthConfigRouteTest.kt
Added back with updated copyright and test. Also edited changelog to mention auth config field name change.

2023-12-19 04:57 UTC, charlta approved these changes

2023-12-19 04:58 UTC, merged