Fixing auth verification for user
zepben/evolve-conn-jvm pull request #14
Opened 2024-02-28 13:32 UTC by alourie

# Description

Fixing auth flow for the Auth0.

* User is created with the token embedded in the attributes field.
* In the handler, the original Jwt verification call is used to match the required claims to the ones in the token. 

### Code
- [x] I have performed a self review of my own code (including checking issues raised when creating the PR).
~- [ ] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.~
~- [ ] I have commented my code in any hard-to-understand or hacky areas.~
- [x] I have handled all new warnings generated by the compiler or IDE.
- [x] I have rebased onto the target branch (usually main).

2024-02-29 02:33 UTC, kgreav requested changes
can you update the changelog plz

2024-02-29 02:49 UTC, alourie commented
> can you update the changelog plz

Done

2024-04-08 06:48 UTC, kgreav approved these changes

2024-04-08 06:48 UTC, ryanjcoleman commented
Task linked: [DEV-111 Vert.x upgrade in EWB breaks user authorisation](https://app.clickup.com/t/6929263/DEV-111)

2024-04-08 06:48 UTC, merged